#markdown: rdiscount
permalink: /:title/
url: http://myself659.github.io
#highlighter: pygments
highlighter: rouge
name: 沉风网事
description: 沉风 | 与爱相伴，与智慧共舞，创造自己的精彩！
author: 沉风 
email: myself659@163.com
duoshuo: myself659
weibo: myself659
hub: myself659
safe: true
paginate: 50
about: "拖延症患者"
disqus:
  shortname:http-myself659-github-io
